services:
  devel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Mount current project into the container
      - ~/.m2:/root/.m2  # Cache Maven dependencies
    user: "${UID}:${GID}"
    command: mvn clean package -DskipTests 
  debug-admin:
    build:
      context: .
      dockerfile: Dockerfile.debug
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    user: "${UID}:${GID}"
    command: java -jar admin/target/admin-0.0.1-SNAPSHOT.jar
    depends_on:
      - devel
  debug-local:
    build:
      context: .
      dockerfile: Dockerfile.debug
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8081:8080"
    user: "${UID}:${GID}"
    command: java -jar admin/target/admin-0.0.1-SNAPSHOT.jar
    depends_on:
      - devel
